# Pandas - Series

In [2]:
import pandas as pd
import numpy as np

In [3]:
A = pd.Series([1,2,3,4])
A

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
A.shape

(4,)

In [5]:
A.ndim

1

In [6]:
B = pd.Series([[1,2,3], [2]])
B

0    [1, 2, 3]
1          [2]
dtype: object

In [7]:
C = pd.Series(['A','B','C','D'])
C

0    A
1    B
2    C
3    D
dtype: object

In [8]:
D = pd.Series([1, 2, 45, 78], index=['a', 'b', 'c', 'd'])
D

a     1
b     2
c    45
d    78
dtype: int64

In [9]:
D[2]

C:\Users\harik\AppData\Local\Temp\ipykernel_15252\1368320093.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  D[2]


45

In [10]:
D['b']

2

In [11]:
D[1:3]

b     2
c    45
dtype: int64

In [12]:
D.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
D.values

array([ 1,  2, 45, 78], dtype=int64)

In [14]:
my_np = np.arange(10)
my_np

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
E = pd.Series(my_np)
E

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [16]:
my_np[3] = 37
my_np

array([ 0,  1,  2, 37,  4,  5,  6,  7,  8,  9])

In [17]:
E

0     0
1     1
2     2
3    37
4     4
5     5
6     6
7     7
8     8
9     9
dtype: int32

In [18]:
s2 = pd.Series([4, -3, np.NaN, 14])
s2

0     4.0
1    -3.0
2     NaN
3    14.0
dtype: float64

In [19]:
s2.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [20]:
s2.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [21]:
s2 = pd.Series([2, 1, 0, 1, 3, 2, 3], index=['white', 'red', 'white', 'orange', 'yellow', 'green', 'pink'])
s2

white     2
red       1
white     0
orange    1
yellow    3
green     2
pink      3
dtype: int64

In [22]:
s2.unique()

array([2, 1, 0, 3], dtype=int64)

In [23]:
s2.value_counts()

2    2
1    2
3    2
0    1
Name: count, dtype: int64

In [24]:
s2['white']

white    2
white    0
dtype: int64

In [25]:

s4 = {'red':400, 'yellow': 2000}
myseries1 = pd.Series(s4)
s5 = {'red': 200, 'black': 1000}
myseries2 = pd.Series(s5)

In [26]:
myseries1 + myseries2

black       NaN
red       600.0
yellow      NaN
dtype: float64