In [5]:
import numpy as np

In [6]:
c = np.array([1,2,3,4,5])

In [7]:
c

array([1, 2, 3, 4, 5])

# 2 dimensional Array

In [8]:
c = np.array([[1,2,3],[4,5,6]])

In [9]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# Rows and Columns
c.shape

(2, 3)

In [11]:
# Dimensional
c.ndim

2

In [12]:
# Datatype of array
c.dtype.name

'int32'

In [13]:
# Size of array
c.size

6

# 3 Dimensional Array

In [14]:
D = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
D.shape

(2, 3, 3)

In [17]:
D.ndim

3

In [18]:
D.dtype.name

'int32'

In [19]:
D.size

18

# Zeros and Ones Array

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.zeros((4, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
np.ones((4, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# Arange Array

In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [26]:
# Start, Stop and Step
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [27]:
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [28]:
np.arange(0,36).reshape(3,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

# Linspace

In [29]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Random

In [30]:
np.random.random(3)

array([0.26644321, 0.54326925, 0.20117072])