In [29]:
import numpy as np

In [30]:
c = np.array([1,2,3,4,5])

In [31]:
c

array([1, 2, 3, 4, 5])

# 2 dimensional Array

In [32]:
c = np.array([[1,2,3],[4,5,6]])

In [33]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# Rows and Columns
c.shape

(2, 3)

In [35]:
# Dimensional
c.ndim

2

In [36]:
# Datatype of array
c.dtype.name

'int32'

In [37]:
# Size of array
c.size

6

# 3 Dimensional Array

In [38]:
D = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [39]:
D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [40]:
D.shape

(2, 3, 3)

In [41]:
D.ndim

3

In [42]:
D.dtype.name

'int32'

In [43]:
D.size

18

# Zeros and Ones Array

In [44]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.zeros((4, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [47]:
np.ones((4, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# Arange Array

In [48]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [50]:
# Start, Stop and Step
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [51]:
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [52]:
np.arange(0,36).reshape(3,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

# Linspace

In [53]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Random

In [54]:
np.random.random(3)

array([0.00141952, 0.51960415, 0.06541647])

In [56]:
random_numbers = np.random.randint(0, 101, 10)

In [57]:
random_numbers

array([43,  2,  0, 93,  4, 18, 98, 92,  7, 83])