In [1]:
import numpy as np

# Arithmetic Operations

In [2]:
a = np.arange(4)

In [3]:
a * 3

array([0, 3, 6, 9])

In [4]:
a + 4

array([4, 5, 6, 7])

In [5]:
b = np.arange(4,8)

In [6]:
b

array([4, 5, 6, 7])

In [7]:
a + b

array([ 4,  6,  8, 10])

In [8]:
a * b

array([ 0,  5, 12, 21])

In [9]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [10]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [11]:
np.sin(b)

array([-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

In [12]:
np.sqrt(b)

array([2.        , 2.23606798, 2.44948974, 2.64575131])

In [14]:
a.dtype.name

'int32'

In [15]:
b.dtype.name

'int32'

In [22]:
c = np.ones((3,3))

In [23]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
c.dtype.name

'float64'