In [24]:
import numpy as np

# Matrix Dot Product

In [25]:
A = np.arange(0,9).reshape(3,3)

In [26]:
B = np.arange(10,19).reshape(3,3)

In [27]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
B

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [29]:
np.dot(A,B)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

In [30]:
np.dot(B,A)

array([[105, 138, 171],
       [132, 174, 216],
       [159, 210, 261]])

In [31]:
A.dot(B)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

# Increment and Decrement Operators

In [32]:
A+=1

In [33]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
A-=1

In [35]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Universal Functions

In [36]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [37]:
np.log(A)

C:\Users\harik\AppData\Local\Temp\ipykernel_9260\2475394391.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(A)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154]])

In [38]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [39]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Aggregate Function

In [40]:
G = np.array([0.5, 2.5, 3.5, 4.5, 5.5])

In [41]:
G

array([0.5, 2.5, 3.5, 4.5, 5.5])

In [42]:
np.sum(G)

16.5

In [43]:
np.min(G)

0.5

In [44]:
np.max(G)

5.5

In [45]:
np.mean(G)

3.3

In [46]:
np.std(G)

1.7204650534085253