In [55]:
import numpy as np

# Matrix Dot Product

In [56]:
A = np.arange(0,9).reshape(3,3)

In [57]:
B = np.arange(10,19).reshape(3,3)

In [58]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
B

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [60]:
np.dot(A,B)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

In [61]:
np.dot(B,A)

array([[105, 138, 171],
       [132, 174, 216],
       [159, 210, 261]])

In [62]:
A.dot(B)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

# Increment and Decrement Operators

In [63]:
A+=1

In [64]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
A-=1

In [66]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Universal Functions

In [67]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [68]:
np.log(A)

C:\Users\harik\AppData\Local\Temp\ipykernel_8124\2475394391.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(A)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154]])

In [69]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [70]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Aggregate Function

In [71]:
G = np.array([0.5, 2.5, 3.5, 4.5])

In [72]:
G

array([0.5, 2.5, 3.5, 4.5])

In [73]:
np.sum(G)

11.0

In [74]:
np.min(G)

0.5

In [75]:
np.max(G)

4.5

In [76]:
np.mean(G)

2.75

In [77]:
np.std(G)

1.479019945774904

# 2 Dimensional Array

In [79]:
H = np.array([[0.5, 2.5], [3.5, 4.5]])

In [80]:
H.ndim

2

In [81]:
H.std()

1.479019945774904