In [1]:
import numpy as np

# Indexing - 1D Array

In [2]:
B = np.arange(1,7)

In [3]:
B

array([1, 2, 3, 4, 5, 6])

In [4]:
B[4]

5

In [5]:
B[-1]

6

In [6]:
B[[0,2,3]]

array([1, 3, 4])

# Indexing - 2D Array

In [7]:
A = np.arange(0,9).reshape(3,3)

In [8]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
A[1,2]

5

In [10]:
A[[[1,2], [2,1], [1,0]]]

array([[[3, 4, 5],
        [6, 7, 8]],

       [[6, 7, 8],
        [3, 4, 5]],

       [[3, 4, 5],
        [0, 1, 2]]])

In [11]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])