In [46]:
import numpy as np

# Slicing - 1D Array

In [47]:
A = np.arange(10,16)

In [48]:
A

array([10, 11, 12, 13, 14, 15])

In [49]:
# Start index as 0
# End index as max length of A
# Step Size as 2
A[::2]

array([10, 12, 14])

In [50]:
# Start index as 1
# End index as max length of A
# Step Size as 1
A[1::]

array([11, 12, 13, 14, 15])

In [51]:
# Start index as 0
# End index as 3
# Step Size as 1
A[:3:]

array([10, 11, 12])

In [52]:
# Start index as 1
# End index as 5
# Step Size as 2
A[1:5:2]

array([11, 13])

# Slicing - 2D Array

In [53]:
A = np.arange(10,26).reshape(4,4)

In [54]:
A

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [55]:
# All Rows
# All Columns
A[:,:]

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [56]:
# First Row (start:stop:step)
# All Columns (start:stop:step)
A[0,:]

array([10, 11, 12, 13])

In [57]:
# Second Row (start:stop:step)
# All Columns (start:stop:step)
A[1,:]

array([14, 15, 16, 17])

In [58]:
# Third Row  (start:stop:step)
# All Columns (start:stop:step)
A[2,:]

array([18, 19, 20, 21])

In [59]:
# Two Rows (start:stop:step)
# All Columns (start:stop:step)
A[:2,:]

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [60]:
# Two Rows (start:stop:step)
# Two Columns (start:stop:step)
A[:2,:2]

array([[10, 11],
       [14, 15]])

In [61]:
# Two Rows (start:stop:step)
# Two Columns (start:stop:step)
A[::2,::2]

array([[10, 12],
       [18, 20]])