In [1]:
import numpy as np

# Slicing - 1D Array

In [2]:
A = np.arange(10,16)

In [3]:
A

array([10, 11, 12, 13, 14, 15])

In [4]:
# Start index as 0
# End index as max length of A
# Step Size as 2
A[::2]

array([10, 12, 14])

In [5]:
# Start index as 1
# End index as max length of A
# Step Size as 1
A[1::]

array([11, 12, 13, 14, 15])

In [6]:
# Start index as 0
# End index as 3
# Step Size as 1
A[:3:]

array([10, 11, 12])

In [7]:
# Start index as 1
# End index as 5
# Step Size as 2
A[1:5:2]

array([11, 13])

# Slicing - 2D Array

In [8]:
A = np.arange(10,26).reshape(4,4)

In [9]:
A

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [10]:
# All Rows
# All Columns
A[:,:]

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [11]:
# First Row (start:stop:step)
# All Columns (start:stop:step)
A[0,:]

array([10, 11, 12, 13])

In [12]:
# Second Row (start:stop:step)
# All Columns (start:stop:step)
A[1,:]

array([14, 15, 16, 17])

In [13]:
# Third Row  (start:stop:step)
# All Columns (start:stop:step)
A[2,:]

array([18, 19, 20, 21])

In [14]:
# Two Rows (start:stop:step)
# All Columns (start:stop:step)
A[:2,:]

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [15]:
# Two Rows (start:stop:step)
# Two Columns (start:stop:step)
A[:2,:2]

array([[10, 11],
       [14, 15]])

In [16]:
# Two Rows (start:stop:step)
# Two Columns (start:stop:step)
A[::2,::2]

array([[10, 12],
       [18, 20]])