# Iterating an Array

In [18]:
import numpy as np

In [19]:
# 2D Array
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
for item in A:
    print(item)

[0 1 2]
[3 4 5]
[6 7 8]


In [21]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
7
8


In [22]:
B = np.apply_along_axis(np.mean,axis=1,arr=A)

In [23]:
B

array([1., 4., 7.])

In [24]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
def foo(x):
    return x/2

In [26]:
np.apply_along_axis(foo,axis=1,arr=A)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [27]:
np.apply_along_axis(foo,axis=0,arr=A)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])