# Iterating an Array

In [23]:
import numpy as np

In [24]:
# 2D Array
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
for item in A:
    print(item)

[0 1 2]
[3 4 5]
[6 7 8]


In [26]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
7
8


In [27]:
B = np.apply_along_axis(np.mean,axis=1,arr=A)

In [28]:
B

array([1., 4., 7.])

In [29]:
C = np.apply_along_axis(np.mean,axis=0,arr=A)

In [30]:
C

array([3., 4., 5.])

In [31]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
def foo(x):
    return x/2

In [33]:
np.apply_along_axis(foo,axis=1,arr=A)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [34]:
np.apply_along_axis(foo,axis=0,arr=A)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])