# Conditions and Boolean Arrays

In [1]:
import numpy as np

In [6]:
# 1D array 
# random generates Array with value ranges from 0 to 1
A = np.random.random(12)

A

array([0.97926632, 0.83419436, 0.33802043, 0.58029429, 0.05953803,
       0.56287162, 0.10181276, 0.34056811, 0.41119645, 0.27188272,
       0.21768639, 0.40590403])

In [4]:
A > 0.5

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False, False])

In [5]:
A[A > 0.5]

array([0.70793432, 0.87788931, 0.70825042, 0.79599166, 0.70346789,
       0.81461928, 0.92370622, 0.90871294])

In [8]:
# 2D array
B = np.random.random((4,4))
B

array([[0.14465258, 0.81741981, 0.90229449, 0.13425579],
       [0.69571792, 0.76377134, 0.80971861, 0.995259  ],
       [0.82666158, 0.30141121, 0.40208634, 0.50697304],
       [0.55120575, 0.5431723 , 0.14454157, 0.25383283]])

In [9]:
B[B>0.5]

array([0.81741981, 0.90229449, 0.69571792, 0.76377134, 0.80971861,
       0.995259  , 0.82666158, 0.50697304, 0.55120575, 0.5431723 ])