# Conditions and Boolean Arrays

In [1]:
import numpy as np

In [2]:
# 1D array 
# random generates Array with value ranges from 0 to 1
A = np.random.random(12)

A

array([0.1674635 , 0.96678208, 0.65015425, 0.09052469, 0.85472011,
       0.1431777 , 0.94810567, 0.76345919, 0.3658443 , 0.85615165,
       0.85220015, 0.59922463])

In [3]:
A > 0.5

array([False,  True,  True, False,  True, False,  True,  True, False,
        True,  True,  True])

In [4]:
A[A > 0.5]

array([0.96678208, 0.65015425, 0.85472011, 0.94810567, 0.76345919,
       0.85615165, 0.85220015, 0.59922463])

In [5]:
# 2D array
B = np.random.random((4,4))
B

array([[0.11971443, 0.4531597 , 0.46946846, 0.37281994],
       [0.20629327, 0.96900207, 0.82781168, 0.02449853],
       [0.27666308, 0.01138685, 0.79937266, 0.45651202],
       [0.39262081, 0.99238424, 0.18248574, 0.32517244]])

In [6]:
B[B>0.5]

array([0.96900207, 0.82781168, 0.79937266, 0.99238424])