# Shape Manipulation

In [1]:
import numpy as np

In [2]:
A = np.random.random(9)
A

array([0.08382163, 0.17355466, 0.51241698, 0.19522946, 0.2430612 ,
       0.47002109, 0.73576591, 0.8740989 , 0.62923929])

In [3]:
# Reshape returns a new object
A.reshape(3,3)

array([[0.08382163, 0.17355466, 0.51241698],
       [0.19522946, 0.2430612 , 0.47002109],
       [0.73576591, 0.8740989 , 0.62923929]])

In [4]:
A

array([0.08382163, 0.17355466, 0.51241698, 0.19522946, 0.2430612 ,
       0.47002109, 0.73576591, 0.8740989 , 0.62923929])

In [5]:
# shape change in existing object
A.shape = (3,3)
A

array([[0.08382163, 0.17355466, 0.51241698],
       [0.19522946, 0.2430612 , 0.47002109],
       [0.73576591, 0.8740989 , 0.62923929]])

In [6]:
# Ravel returns a new object (converts 2D to 1D)

A.ravel()

array([0.08382163, 0.17355466, 0.51241698, 0.19522946, 0.2430612 ,
       0.47002109, 0.73576591, 0.8740989 , 0.62923929])

In [7]:
A

array([[0.08382163, 0.17355466, 0.51241698],
       [0.19522946, 0.2430612 , 0.47002109],
       [0.73576591, 0.8740989 , 0.62923929]])

In [8]:
# shape change in existing object
A.shape = (9)
A

array([0.08382163, 0.17355466, 0.51241698, 0.19522946, 0.2430612 ,
       0.47002109, 0.73576591, 0.8740989 , 0.62923929])

# Transpose

In [9]:
A.shape = (3,3)
A

array([[0.08382163, 0.17355466, 0.51241698],
       [0.19522946, 0.2430612 , 0.47002109],
       [0.73576591, 0.8740989 , 0.62923929]])

In [10]:
A.transpose()

array([[0.08382163, 0.19522946, 0.73576591],
       [0.17355466, 0.2430612 , 0.8740989 ],
       [0.51241698, 0.47002109, 0.62923929]])