# Shape Manipulation

In [1]:
import numpy as np

In [4]:
A = np.random.random(9)
A

array([0.77065971, 0.36083982, 0.443043  , 0.0832457 , 0.30418202,
       0.31906861, 0.63498651, 0.12013035, 0.64047905])

In [7]:
# Reshape returns a new object
A.reshape(3,3)

array([[0.77065971, 0.36083982, 0.443043  ],
       [0.0832457 , 0.30418202, 0.31906861],
       [0.63498651, 0.12013035, 0.64047905]])

In [6]:
A

array([0.77065971, 0.36083982, 0.443043  , 0.0832457 , 0.30418202,
       0.31906861, 0.63498651, 0.12013035, 0.64047905])

In [9]:
# shape change in existing object
A.shape = (3,3)
A

array([[0.77065971, 0.36083982, 0.443043  ],
       [0.0832457 , 0.30418202, 0.31906861],
       [0.63498651, 0.12013035, 0.64047905]])

In [10]:
# Ravel returns a new object (converts 2D to 1D)

A.ravel()

array([0.77065971, 0.36083982, 0.443043  , 0.0832457 , 0.30418202,
       0.31906861, 0.63498651, 0.12013035, 0.64047905])

In [11]:
A

array([[0.77065971, 0.36083982, 0.443043  ],
       [0.0832457 , 0.30418202, 0.31906861],
       [0.63498651, 0.12013035, 0.64047905]])

In [13]:
# shape change in existing object
A.shape = (9)
A

array([0.77065971, 0.36083982, 0.443043  , 0.0832457 , 0.30418202,
       0.31906861, 0.63498651, 0.12013035, 0.64047905])

# Transpose

In [16]:
A.shape = (3,3)
A

array([[0.77065971, 0.36083982, 0.443043  ],
       [0.0832457 , 0.30418202, 0.31906861],
       [0.63498651, 0.12013035, 0.64047905]])

In [17]:
A.transpose()

array([[0.77065971, 0.0832457 , 0.63498651],
       [0.36083982, 0.30418202, 0.12013035],
       [0.443043  , 0.31906861, 0.64047905]])