# Joining Arrays

In [148]:
import numpy as np

In [149]:
A = np.arange(9).reshape(3, 3)
B = np.arange(9, 18).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [150]:
B

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [151]:
np.hstack((A,B))

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [152]:
np.vstack((A,B))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [153]:
np.row_stack((A,B))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [154]:
np.column_stack((A,B))

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [155]:
C = np.array([0,1,2,3,4,5,6,7,8])
D = np.array([10,11,12,13,14,15,16,17,18])

C

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [156]:
D

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [157]:
E = np.row_stack((C,D))
E

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [158]:
E.shape

(2, 9)

In [159]:
F = np.column_stack((C,D))
F


array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18]])

In [160]:
F.shape

(9, 2)

In [161]:
G = np.hstack((C,D))
G


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [162]:
G.shape

(18,)

In [163]:
H = np.vstack((C,D))
H

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [164]:
H.shape

(2, 9)