# Copy of Array

In [33]:
import numpy as np

In [34]:
C = np.arange(9).reshape(3,3)
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
D = C
D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
C[1][1] = 10
C

array([[ 0,  1,  2],
       [ 3, 10,  5],
       [ 6,  7,  8]])

In [37]:
D

array([[ 0,  1,  2],
       [ 3, 10,  5],
       [ 6,  7,  8]])

In [38]:
E = np.copy(C)
E

array([[ 0,  1,  2],
       [ 3, 10,  5],
       [ 6,  7,  8]])

In [39]:
C[1][1] = 100

In [40]:
C

array([[  0,   1,   2],
       [  3, 100,   5],
       [  6,   7,   8]])

In [41]:
D

array([[  0,   1,   2],
       [  3, 100,   5],
       [  6,   7,   8]])

In [42]:
E

array([[ 0,  1,  2],
       [ 3, 10,  5],
       [ 6,  7,  8]])

# Structured Arrays

In [43]:
A = np.array([(1,'Array1', 1+3j, 1.4), (2,'Array2', 2+3j, 2.4), (3,'Array3', 3+3j, 3.4), (4,'Array4', 4+3j, 4.4)], dtype=('i2, a7, c8, f4'))
A

array([(1, b'Array1', 1.+3.j, 1.4), (2, b'Array2', 2.+3.j, 2.4),
       (3, b'Array3', 3.+3.j, 3.4), (4, b'Array4', 4.+3.j, 4.4)],
      dtype=[('f0', '<i2'), ('f1', 'S7'), ('f2', '<c8'), ('f3', '<f4')])

In [44]:
A.shape

(4,)

In [45]:
A.ndim

1

In [46]:
B = np.array(([1,'Array1', 1+3j, 1.4],[2,'Array2', 2+3j, 2.4], [3,'Array3', 3+3j, 3.4], [4,'Array4', 4+3j, 4.4]))
B

array([['1', 'Array1', '(1+3j)', '1.4'],
       ['2', 'Array2', '(2+3j)', '2.4'],
       ['3', 'Array3', '(3+3j)', '3.4'],
       ['4', 'Array4', '(4+3j)', '4.4']], dtype='<U64')

In [47]:
B.shape

(4, 4)

In [48]:
B.ndim

2